/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AvMap: typeof import('./components/AvMap.vue')['default']
    AvMapInfoWindow: typeof import('./components/AvMapInfoWindow.vue')['default']
    AvMapMarker: typeof import('./components/AvMapMarker.vue')['default']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    IEpAim: typeof import('~icons/ep/aim')['default']
  }
}
